import {
  densityMatrix,
  concurrence,
  purity,
  bellFromInput,
  inputFromBell,
  stateLabel,
  stateEquation,
  stateEquationBody,
  partialTrace0,
  partialTrace1,
  blochVector,
  applyLocalRotation,
  classifyState,
} from './state.js';
import { createMatrixGrid } from './matrix-grid.js';
import { createBlochSpheres } from './bloch-sphere.js';
import { createCircuitDiagram } from './circuit-diagram.js';
import { buildExportPayload } from './export.js';
import { EXPORT_TARGETS, loadCircuitExport } from './circuit-export.js';
import { translate } from './i18n.js';
import { loadManifest, loadLocaleBundle, detectLocale } from './locale-loader.js';
import en from '../locales/en.js';

const LOCALE_STORAGE_KEY = 'bell-state-locale';

// `en` is always the fallback bundle, so any locale — including a partial
// PR-contributed one — degrades to English per-key rather than breaking.
// `activeLocale` starts as `en` so the first paint is never blank while
// initLocale() resolves a saved preference or auto-detected match.
let activeLocale = en;

/** Shorthand for translate() against the currently active locale. */
function t(key, params) {
  return translate(activeLocale.strings, en.strings, key, params);
}

/** Resolves a flat list of keys under `namespace` into a { key: text } bag,
 * the shape matrix-grid.js/bloch-sphere.js/circuit-diagram.js's draw()
 * functions expect for their `strings` parameter. */
function resolveStrings(namespace, keys) {
  const result = {};
  keys.forEach((key) => {
    result[key] = t(`${namespace}.${key}`);
  });
  return result;
}

const model = {
  q0: 0,
  q1: 0,
  theta: Math.PI / 4,
  dephasing: 0,
  rotation0: 0,
  rotation1: 0,
};

const dom = {};
let draw;
let drawBloch;
let drawCircuit;
let bellRows;

function query() {
  [
    'grid',
    'q0',
    'q1',
    'phase',
    'family',
    'dephasing',
    'dephasing-value',
    'theta',
    'theta-value',
    'state-label',
    'concurrence',
    'purity',
    'bell-state-list',
    'reading',
    'bloch-spheres',
    'circuit-diagram',
    'local-rotation',
    'local-rotation-value',
    'local-rotation-1',
    'local-rotation-1-value',
    'reset',
    'export-state',
    'circuit-export-target',
    'export-circuit',
    'export-circuit-status',
    'locale-picker',
  ].forEach((id) => {
    dom[id] = document.getElementById(id);
  });
}

function toggleBit(which) {
  model[which] = model[which] === 1 ? 0 : 1;
  render();
}

/**
 * Both toggle pairs write the same two bits, so pressing "phase" moves q0 and
 * vice versa. Buttons carry aria-pressed so the coupling is announced too.
 */
function setPair(button, pressed, label) {
  button.textContent = label;
  button.setAttribute('aria-pressed', String(pressed));
}

/**
 * Fills the four bell-row ket/equation spans from state.js's own formulas
 * instead of the hardcoded HTML they replaced — one source of truth, and
 * these are math notation generated by code rather than translatable prose,
 * so they need no locale handling at all. Static per Bell-state identity
 * (doesn't depend on model), so this runs once at init, not on every render.
 */
function populateBellRows() {
  bellRows.forEach((row) => {
    const [family, sign] = row.dataset.state.split('-');
    const psi = family === 'psi';
    const negative = sign === 'minus';
    row.querySelector('.bell-ket').textContent = stateLabel({ psi, negative });
    row.querySelector('.bell-eq').textContent = `= ${stateEquationBody({ psi, negative })}`;
  });
}

/** Add `bundle` as a picker option if it isn't already listed (covers a
 * locale that was auto-detected or manually loaded but never made it into
 * locales/manifest.json). */
function ensureOption(bundle) {
  const select = dom['locale-picker'];
  const exists = Array.from(select.options).some((o) => o.value === bundle.meta.code);
  if (!exists) {
    const option = document.createElement('option');
    option.value = bundle.meta.code;
    option.textContent = bundle.meta.endonym || bundle.meta.englishName || bundle.meta.code;
    select.appendChild(option);
  }
}

/**
 * Applies every [data-i18n]-tagged static element in one pass, plus the two
 * document-level pieces (title, meta description) that aren't inside <body>
 * or don't use textContent. Static chrome only — anything that depends on
 * model state (button labels, readouts) is handled in render() instead.
 */
function applyStaticText() {
  document.title = t('ui.docTitle');
  document.querySelector('meta[name="description"]')?.setAttribute('content', t('ui.metaDescription'));
  document.querySelectorAll('[data-i18n]').forEach((el) => {
    el.textContent = t(el.dataset.i18n);
  });
}

function applyLocale(bundle) {
  activeLocale = bundle;
  document.documentElement.lang = bundle.meta.code;
  document.documentElement.dir = bundle.meta.direction;
  ensureOption(bundle);
  dom['locale-picker'].value = bundle.meta.code;
  applyStaticText();
  render();
}

function populatePicker(manifestEntries) {
  const select = dom['locale-picker'];
  const existing = new Set(Array.from(select.options).map((o) => o.value));
  manifestEntries.forEach((entry) => {
    if (existing.has(entry.code)) return;
    const option = document.createElement('option');
    option.value = entry.code;
    option.textContent = entry.endonym || entry.englishName || entry.code;
    select.appendChild(option);
  });
}

async function onLocaleChange(code) {
  if (code === 'en') {
    applyLocale(en);
    localStorage.setItem(LOCALE_STORAGE_KEY, 'en');
    return;
  }
  const bundle = await loadLocaleBundle(code);
  if (!bundle) {
    dom['locale-picker'].value = activeLocale.meta.code;
    return;
  }
  applyLocale(bundle);
  localStorage.setItem(LOCALE_STORAGE_KEY, code);
}

/**
 * Populates the picker from locales/manifest.json, then resolves the active
 * locale: an explicit saved preference wins over auto-detection, which in
 * turn is tried independently of the manifest (see locale-loader.js) so a
 * bundle file copied straight into locales/ is found even with no manifest
 * entry at all. Runs after the first synchronous English render, so a slow
 * or failed fetch never blocks the initial paint.
 */
async function initLocale() {
  const manifest = await loadManifest();
  populatePicker(manifest);

  const saved = localStorage.getItem(LOCALE_STORAGE_KEY);
  if (saved && saved !== 'en') {
    const bundle = await loadLocaleBundle(saved);
    if (bundle) {
      applyLocale(bundle);
      return;
    }
  }
  if (saved === 'en') return;

  const detected = await detectLocale(navigator.languages || [navigator.language]);
  if (detected) applyLocale(detected.bundle);
}

function render() {
  const { psi, negative } = bellFromInput(model.q0, model.q1);
  // Compute Bell state (with dephasing), then apply local rotation to q0.
  // Concurrence is evaluated on the pre-rotation state because the Bell-state
  // formula is only valid for that structure; local unitaries preserve entanglement.
  const baseRho = densityMatrix({
    psi,
    negative,
    theta: model.theta,
    dephasing: model.dephasing,
  });
  const rho = applyLocalRotation(
    applyLocalRotation(baseRho, model.rotation0, 0),
    model.rotation1, 1,
  );

  draw(rho, resolveStrings('matrixGrid', [
    'svgTitle', 'svgDescIntro', 'tableCaption', 'entryTemplate', 'summaryTemplate', 'joinText', 'allZero',
  ]));

  setPair(dom.q0, model.q0 === 1, t('ui.qubitEquals', { qubit: 'q0', value: model.q0 }));
  setPair(dom.q1, model.q1 === 1, t('ui.qubitEquals', { qubit: 'q1', value: model.q1 }));
  setPair(dom.phase, negative, t('ui.phaseSign', { sign: negative ? '−' : '+' }));
  setPair(dom.family, psi, t('ui.familyLabel', { family: psi ? 'Ψ' : 'Φ' }));

  const degrees = Math.round((model.theta * 180) / Math.PI);
  const percent = Math.round(model.dephasing * 100);
  const rot0Deg = Math.round((model.rotation0 * 180) / Math.PI);
  const rot1Deg = Math.round((model.rotation1 * 180) / Math.PI);
  dom['theta-value'].textContent = t('ui.degrees', { value: degrees });
  dom['dephasing-value'].textContent = t('ui.percent', { value: percent });
  dom['local-rotation-value'].textContent = t('ui.degrees', { value: rot0Deg });
  dom['local-rotation-1-value'].textContent = t('ui.degrees', { value: rot1Deg });

  const conc = concurrence(baseRho);  // Bell-state formula; entanglement is rotation-invariant
  const pur = purity(rho);

  const label = stateLabel({ psi, negative });
  dom['state-label'].textContent = stateEquation({ psi, negative });
  dom.concurrence.textContent = conc.toFixed(2);
  dom.purity.textContent = pur.toFixed(2);

  const bellKey = `${psi ? 'psi' : 'phi'}-${negative ? 'minus' : 'plus'}`;
  bellRows.forEach((row) => {
    row.classList.toggle('current', row.dataset.state === bellKey);
  });
  const regimeKey = classifyState({ conc, pur, dephasing: model.dephasing, theta: model.theta });
  dom.reading.textContent = t(`interpret.${regimeKey}`);

  drawBloch(
    blochVector(partialTrace0(rho)),
    blochVector(partialTrace1(rho)),
    resolveStrings('blochSphere', ['origin', 'vector']),
  );
  drawCircuit(
    { q0: model.q0, q1: model.q1, label, alpha0: model.rotation0, alpha1: model.rotation1 },
    resolveStrings('circuitDiagram', ['description']),
  );
}

function downloadBlob(filename, blob) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function downloadJson(filename, payload) {
  downloadBlob(filename, new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' }));
}

function downloadText(filename, text, mimeType) {
  downloadBlob(filename, new Blob([text], { type: mimeType }));
}

function exportState() {
  const payload = buildExportPayload(model);
  const { psi, negative } = bellFromInput(model.q0, model.q1);
  const bellKey = `${psi ? 'psi' : 'phi'}-${negative ? 'minus' : 'plus'}`;
  const timestamp = payload.exportedAt.replace(/[:.]/g, '-');
  downloadJson(`bell-state-${bellKey}-${timestamp}.json`, payload);
}

/** Vendor/format names ("Qiskit (Python)", "OpenQASM 2.0") are proper nouns,
 * not translated content — same rationale as index.html's own-language
 * <option> in the locale picker. Runs once at init(); the registry itself
 * never changes at runtime. */
function populateCircuitExportTargets() {
  const select = dom['circuit-export-target'];
  EXPORT_TARGETS.forEach((target) => {
    const option = document.createElement('option');
    option.value = target.id;
    option.textContent = target.label;
    select.appendChild(option);
  });
}

async function exportCircuit() {
  dom['export-circuit-status'].textContent = '';
  try {
    const { content, filename, mimeType } = await loadCircuitExport(
      dom['circuit-export-target'].value,
      model,
    );
    downloadText(filename, content, mimeType);
  } catch {
    dom['export-circuit-status'].textContent = t('ui.exportCircuitError');
  }
}

function init() {
  query();
  applyStaticText();
  draw = createMatrixGrid(dom.grid);
  drawBloch = createBlochSpheres(dom['bloch-spheres']);
  drawCircuit = createCircuitDiagram(dom['circuit-diagram']);
  bellRows = dom['bell-state-list'].querySelectorAll('.bell-row');
  populateBellRows();
  populateCircuitExportTargets();

  dom.q0.addEventListener('click', () => toggleBit('q0'));
  dom.phase.addEventListener('click', () => toggleBit('q0'));
  dom.q1.addEventListener('click', () => toggleBit('q1'));
  dom.family.addEventListener('click', () => toggleBit('q1'));

  dom.dephasing.addEventListener('input', (e) => {
    model.dephasing = Number(e.target.value) / 100;
    render();
  });

  dom.theta.addEventListener('input', (e) => {
    model.theta = (Number(e.target.value) * Math.PI) / 180;
    render();
  });

  dom['local-rotation'].addEventListener('input', (e) => {
    model.rotation0 = (Number(e.target.value) * Math.PI) / 180;
    render();
  });

  dom['local-rotation-1'].addEventListener('input', (e) => {
    model.rotation1 = (Number(e.target.value) * Math.PI) / 180;
    render();
  });

  dom['export-state'].addEventListener('click', exportState);
  dom['export-circuit'].addEventListener('click', exportCircuit);

  dom['locale-picker'].addEventListener('change', (e) => onLocaleChange(e.target.value));

  dom.reset.addEventListener('click', () => {
    model.q0 = 0;
    model.q1 = 0;
    model.theta = Math.PI / 4;
    model.dephasing = 0;
    model.rotation0 = 0;
    model.rotation1 = 0;

    dom.dephasing.value = '0';
    dom.theta.value = '45';
    dom['local-rotation'].value = '0';
    dom['local-rotation-1'].value = '0';

    render();
  });

  render();
  initLocale();
}

document.addEventListener('DOMContentLoaded', init);

export { model, inputFromBell };
